/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCAdminRole;

import Business.EcoSystem;
import Business.FCWarehouse.FCWarehouse;
import Business.NGO.NGO;
import Business.NGOVolunteer.VolRequests;
import Business.NGOVolunteer.VolRequestsDirectory;
import Business.NGOVolunteer.Volunteer;
import Business.NGOVolunteer.VolunteerDirectory;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sowmyachinimilli
 */
public class ManageVolunteerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVolunteerPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    VolunteerDirectory vold;
    VolRequestsDirectory vrD;
    String WHname;
    public ManageVolunteerPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        populateTable();
         if(ecosystem.getVRDirectory() == null){
         ecosystem.setVRDirectory(new VolRequestsDirectory());
        }
        ArrayList<String> ngoList = new ArrayList();
        for (NGO ng : ecosystem.getNgoDir().getNgoList()){
            ngoList.add(ng.getNgoName());
        }
        cbV.setModel(new DefaultComboBoxModel<String>(ngoList.toArray(new String[0])));
        for(FCWarehouse fcw: ecosystem.getFCWDirectory().getFcwList()){
            if(fcw.getFcwAdmin().equals(userAcc.getEmployee().getName())){
                WHname=fcw.getFcwName();
            }
        }

        lblq.setVisible(false);
        cbQ.setVisible(false);

        setBG();
        makeTableTransparent();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDonProfileTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVolunteer = new javax.swing.JTable();
        lblDonProfileTitle1 = new javax.swing.JLabel();
        lblq = new javax.swing.JLabel();
        cbQ = new javax.swing.JComboBox<>();
        btnReq = new javax.swing.JButton();
        lblq1 = new javax.swing.JLabel();
        cbV = new javax.swing.JComboBox<>();
        LabelImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblDonProfileTitle.setFont(new java.awt.Font("Georgia", 1, 29)); // NOI18N
        lblDonProfileTitle.setForeground(new java.awt.Color(51, 153, 255));
        lblDonProfileTitle.setText("Manage Volunteers");

        tblVolunteer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Volunteer Id", "Name", "Phone Number", "Address", "City", "Zipcode", "Available?"
            }
        ));
        tblVolunteer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblVolunteerMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblVolunteer);

        lblDonProfileTitle1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblDonProfileTitle1.setForeground(new java.awt.Color(51, 153, 255));
        lblDonProfileTitle1.setText("Request Volunteers");

        lblq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblq.setText("Number of Volunteers Required :");

        cbQ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "1", "2", "3", "4", "5" }));

        btnReq.setText("Submit Request");
        btnReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqActionPerformed(evt);
            }
        });

        lblq1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblq1.setText("Select a NGO :");

        cbV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1427, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(lblDonProfileTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(cbV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(lblq1))
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(lblDonProfileTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(lblq))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(btnReq))
            .addComponent(LabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 1430, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(cbQ, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblDonProfileTitle1)
                .addGap(31, 31, 31)
                .addComponent(cbV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(lblq1))
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(cbQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblDonProfileTitle))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(lblq))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(btnReq))
            .addComponent(LabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

        public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {

        }
    }

    public void makeTableTransparent() {
        tblVolunteer.setOpaque(false);
        ((DefaultTableCellRenderer) tblVolunteer.getDefaultRenderer(Object.class)).setOpaque(false);
        tblVolunteer.setShowGrid(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblVolunteer.getModel().getColumnCount(); i++) {
            tblVolunteer.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    private void btnReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqActionPerformed
        // TODO add your handling code here:
        VolRequests vr = new VolRequests();
        vr.setVolreqId("1");
        vr.setVolreqName(cbV.getSelectedItem().toString());
        vr.setVolreqNum("1");
        vr.setVolreqWH(WHname);
        vr.setVolreqStatus("Requested");
        vrD = ecosystem.getVRDirectory();
        vrD.addVR(vr);
       ecosystem.setVRDirectory(vrD);
        JOptionPane.showMessageDialog(this, "Your request has been sent to NGO");
    }//GEN-LAST:event_btnReqActionPerformed

    private void tblVolunteerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVolunteerMousePressed
        // TODO add your handling code here:
        tblVolunteer.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblVolunteerMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JButton btnReq;
    private javax.swing.JComboBox<String> cbQ;
    private javax.swing.JComboBox<String> cbV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDonProfileTitle;
    private javax.swing.JLabel lblDonProfileTitle1;
    private javax.swing.JLabel lblq;
    private javax.swing.JLabel lblq1;
    private javax.swing.JTable tblVolunteer;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblVolunteer.getModel();
        model.setRowCount(0);
        for(Volunteer vol: ecosystem.getVolDir().getVolunteerList()){
           Object[] row = new Object[7];
           row[0] =vol;
           row[1] =vol.getVolName();
           row[2] =vol.getVolPhno();
           row[3] =vol.getVolAddress();
           row[4] =vol.getVolCity();
           row[5] =vol.getVolZipcode();
           row[6] =vol.getVolAvail();
           model.addRow(row);
        } 
    }
}
