/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCPManagerRole;

import Business.EcoSystem;
import Business.FCPantry.FCPantryItems;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sowmyachinimilli
 */
public class PantryStockPanel extends javax.swing.JPanel {

    /**
     * Creates new form PantryStockPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    public PantryStockPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        populatePantryItemsTable();
         lblq.setVisible(false);
         lblq1.setVisible(false);
         cbQ.setVisible(false);
         btnReq.setVisible(false);
         chkReq.setVisible(false);
         setBG();
         makeTableTransparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddFCPTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblitems = new javax.swing.JTable();
        btnReq = new javax.swing.JButton();
        lblq = new javax.swing.JLabel();
        cbQ = new javax.swing.JComboBox<>();
        chkReq = new javax.swing.JCheckBox();
        lblq1 = new javax.swing.JLabel();
        LabelImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddFCPTitle.setFont(new java.awt.Font("Georgia", 1, 29)); // NOI18N
        lblAddFCPTitle.setForeground(new java.awt.Color(51, 153, 255));
        lblAddFCPTitle.setText("Available Stock");
        add(lblAddFCPTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        tblitems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Id", "Food Item", "Item Quantity"
            }
        ));
        tblitems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblitemsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblitems);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1008, 153));

        btnReq.setText("Submit Request");
        btnReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqActionPerformed(evt);
            }
        });
        add(btnReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 369, -1, -1));

        lblq.setText("Quantity Required for:");
        add(lblq, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 315, -1, -1));

        cbQ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "50", "100", "150", "200", "250" }));
        add(cbQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 311, 120, -1));

        chkReq.setText("Request stock from Warehouse");
        chkReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkReqActionPerformed(evt);
            }
        });
        add(chkReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        lblq1.setText("Persons");
        add(lblq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));
        add(LabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 690));
    }// </editor-fold>//GEN-END:initComponents

    
       public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {

        }
    }

    public void makeTableTransparent() {
        tblitems.setOpaque(false);
        ((DefaultTableCellRenderer) tblitems.getDefaultRenderer(Object.class)).setOpaque(false);
        tblitems.setShowGrid(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblitems.getModel().getColumnCount(); i++) {
            tblitems.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    
    private void chkReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkReqActionPerformed
        // TODO add your handling code here:
        if(chkReq.isSelected()){
            lblq.setVisible(true);
            lblq1.setVisible(true);
            cbQ.setVisible(true);
            btnReq.setVisible(true);
        }
        else{
            lblq.setVisible(false);
            lblq1.setVisible(false);
            cbQ.setVisible(false);
            btnReq.setVisible(false);
        }
    }//GEN-LAST:event_chkReqActionPerformed

    private void btnReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Your request has been sent to Warehouse");
    }//GEN-LAST:event_btnReqActionPerformed

    private void tblitemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblitemsMousePressed
        // TODO add your handling code here:
        tblitems.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblitemsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JButton btnReq;
    private javax.swing.JComboBox<String> cbQ;
    private javax.swing.JCheckBox chkReq;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddFCPTitle;
    private javax.swing.JLabel lblq;
    private javax.swing.JLabel lblq1;
    private javax.swing.JTable tblitems;
    // End of variables declaration//GEN-END:variables

    private void populatePantryItemsTable() {
        DefaultTableModel model = (DefaultTableModel) tblitems.getModel();
        model.setRowCount(0);
        for(FCPantryItems fcpi: ecosystem.getFCPIDirectory().getFcpiList()){
            if(fcpi.getPantryManager().equals(userAcc.getEmployee().getName())){
           Object[] row = new Object[3];
           row[0] =fcpi;
           row[1] =fcpi.getFoodItem();
           row[2] =fcpi.getFoodQuan();
           model.addRow(row);
            }
        } 
    }
}
