/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCPManagerRole;

import Business.EcoSystem;
import Business.NGOVolunteer.Volunteer;
import Business.Reqorder.Reqorder;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sowmyachinimilli
 */
public class ViewFoodRequestsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFoodRequestsPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    String volname;
    public ViewFoodRequestsPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        populateTable();
         setBG();
         makeTableTransparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDonProfileTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFdReqs = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        lblRid = new javax.swing.JLabel();
        txtDRid = new javax.swing.JTextField();
        lblDRid1 = new javax.swing.JLabel();
        cbVol = new javax.swing.JComboBox<>();
        btnSend = new javax.swing.JButton();
        lblDonProfileTitle1 = new javax.swing.JLabel();
        LabelImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDonProfileTitle.setFont(new java.awt.Font("Georgia", 1, 29)); // NOI18N
        lblDonProfileTitle.setForeground(new java.awt.Color(51, 153, 255));
        lblDonProfileTitle.setText("Food Requests");
        add(lblDonProfileTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 32, -1, -1));

        tblFdReqs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request Id", "Requestor", "Quantity", "Order Type", "Status"
            }
        ));
        tblFdReqs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblFdReqsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblFdReqs);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, 999, 153));

        btnAssign.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 469, -1, -1));

        lblRid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRid.setText("Request ID :");
        add(lblRid, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 380, -1, -1));

        txtDRid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDRid.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDRid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDRidFocusLost(evt);
            }
        });
        txtDRid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDRidKeyReleased(evt);
            }
        });
        add(txtDRid, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 376, 137, -1));

        lblDRid1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDRid1.setText("Assign Volunteer :");
        add(lblDRid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 423, -1, -1));

        cbVol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 419, 137, -1));

        btnSend.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSend.setText("Send request to volunteer");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 286, -1, -1));

        lblDonProfileTitle1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblDonProfileTitle1.setForeground(new java.awt.Color(51, 153, 255));
        lblDonProfileTitle1.setText("Assign Volunteer");
        add(lblDonProfileTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 302, -1, -1));
        add(LabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 670));
    }// </editor-fold>//GEN-END:initComponents

           public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {

        }
    }

    public void makeTableTransparent() {
        tblFdReqs.setOpaque(false);
        ((DefaultTableCellRenderer) tblFdReqs.getDefaultRenderer(Object.class)).setOpaque(false);
        tblFdReqs.setShowGrid(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblFdReqs.getModel().getColumnCount(); i++) {
            tblFdReqs.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    private void txtDRidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDRidFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDRidFocusLost

    private void txtDRidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDRidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDRidKeyReleased

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblFdReqs.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a request");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblFdReqs.getModel();
        Reqorder selectedR = (Reqorder)model.getValueAt(selectedRowIndex, 0);
        txtDRid.setText(selectedR.getReqOrderId());
        ArrayList<String> VolunteerList = new ArrayList();
        for (Volunteer vol : ecosystem.getVolDir().getVolunteerList()){
            VolunteerList.add(vol.getVolName());
        }
        cbVol.setModel(new DefaultComboBoxModel<String>(VolunteerList.toArray(new String[0])));
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblFdReqs.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a request");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblFdReqs.getModel();
        Reqorder selectedR = (Reqorder)model.getValueAt(selectedRowIndex, 0);
        volname= cbVol.getSelectedItem().toString();
        selectedR.setReqVol(cbVol.getSelectedItem().toString());
        selectedR.setReqOrderStatus("Assigned to Volunteer");
        for(Volunteer v:ecosystem.getVolDir().getVolunteerList()){
            if(v.getVolName().equals(volname)){
                v.setVolAvail("No");
            }
        }
        JOptionPane.showMessageDialog(this, "Pickup Request Assigned to Volunteer Successfully!");
    }//GEN-LAST:event_btnAssignActionPerformed

    private void tblFdReqsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFdReqsMousePressed
        // TODO add your handling code here:
      tblFdReqs.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblFdReqsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox<String> cbVol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDRid1;
    private javax.swing.JLabel lblDonProfileTitle;
    private javax.swing.JLabel lblDonProfileTitle1;
    private javax.swing.JLabel lblRid;
    private javax.swing.JTable tblFdReqs;
    private javax.swing.JTextField txtDRid;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblFdReqs.getModel();
        model.setRowCount(0);
        for(Reqorder rq: ecosystem.getReqorderDirectory().getReqOrderList()){
           Object[] row = new Object[5];
           row[0] =rq;
           row[1] =rq.getReqName();
           row[2] =rq.getReqOrderQuant();
           row[3] =rq.getReqOrderType();
           row[4] =rq.getReqOrderStatus();
           model.addRow(row);
        } 
    }
}
